// Code generated by cmd/gen --src_dir ../container --src_type Container --dest_type Graphics --dest_package graphics. DO NOT EDIT.
package graphics

import (
	"github.com/negasus/pixigo"
	"github.com/negasus/pixigo/observable"
)

func (v *Graphics) AddChild(c ...pixigo.Container) {
	for _, child := range c {
		v.jsv.Call("addChild", child.JSV())
	}
}
func (v *Graphics) X() float64 {
	return v.jsv.Get("x").Float()
}
func (v *Graphics) Y() float64 {
	return v.jsv.Get("y").Float()
}
func (v *Graphics) SetX(x float64) {
	v.jsv.Set("x", x)
}
func (v *Graphics) SetY(y float64) {
	v.jsv.Set("y", y)
}
func (v *Graphics) Pivot() *observable.Point {
	return v.pivot
}
func (v *Graphics) Width() float64 {
	return v.jsv.Get("width").Float()
}
func (v *Graphics) Height() float64 {
	return v.jsv.Get("height").Float()
}
func (v *Graphics) SetRotation(i float64) {
	v.jsv.Set("rotation", i)
}
func (v *Graphics) Rotation() float64 {
	return v.jsv.Get("rotation").Float()
}
func (v *Graphics) Position() *observable.Point {
	return v.position
}
